Iter14
netzen86/collectmetrics pull request #15
Opened 2024-09-23 18:16 UTC by netzen86

added sing data in request in agent and added sing in response and check equal sing in server.

2024-09-29 10:53 UTC, Ropho commented on cmd/server/main.go
> +	"github.com/netzen86/collectmetrics/internal/db"
стоит отделать пустой строкой библиотеки внутренние и библиотеки внешние (импортируемые извне)

2024-09-29 10:57 UTC, MeneTelk0 commented
Первое и самое важное замечание:
Агент отправляет данные на сервер только посредством API сервера. У Агента нет и не должно быть доступа ни к базе данных сервера, ни к файловому хранилищу, ни к in-memory хранилищу

То есть мы очень четко разделяем логику работы наших сервисов (агента и сервера) и не мешаем ее друг с другом. Агент – только собирает метрики и передает их на сервер (посредством API). Сервер – хранит метрики (в памяти, в файле, в бд) и обрабатывает запросы по API.

Часть дальнейшего рефакторинга будет нацелена на исправление этого

2024-09-29 13:22 UTC, Ropho commented on cmd/server/main.go
> +)
информацию по настройкам севрера стоит перенести в файл конфигурации приложения и сделать обработку этого файла отдельным пакетом config

2024-09-29 13:31 UTC, Ropho commented on cmd/agent/main.go
> +	reportInterval     int    = 10
лучше использовать типы и названия которые отражают размерность
time.Duration к примеру

2024-10-01 09:28 UTC, netzen86 commented on cmd/server/main.go
> +	"github.com/netzen86/collectmetrics/internal/db"
Горотово отделил

2024-10-01 17:50 UTC, netzen86 commented on cmd/server/main.go
> +)
Выделил получение настроек сервера из флагов и переменных окружения в отдельный пакет

2024-10-01 17:50 UTC, netzen86 commented on cmd/agent/main.go
> +	reportInterval     int    = 10
Частично получилось сделать в константе но при получении флагов все равно пришлось использовать переменные типа int

2024-10-02 09:26 UTC, Ropho commented on cmd/agent/main.go
> +	// устанвливаем для отображения даты и времени в логах
опечатка в слове "устанавливаем"

2024-10-02 09:31 UTC, Ropho commented on config/agentcfg.go
> +	"github.com/spf13/pflag"
правила  импортов такие

пакеты стандартной бибилотеки
пустая строка
пакеты внешних сторонних библиотек
пустая строка
библиотеки нашего сервиса

2024-10-02 09:32 UTC, Ropho commented on config/agentcfg.go
> +}
очень круто

2024-10-02 09:59 UTC, Ropho commented on config/agentcfg.go
> +
FYI можно вынести логику выставления env в отдельную фукнцию
Не крит

2024-10-02 10:03 UTC, Ropho commented on internal/agent/agent.go
> +)
это же дефолтные значения?
Лучше перенести их в файл конфига

2024-10-02 10:05 UTC, Ropho commented on internal/agent/agent.go
> +	runtime.GC()
лучше так все же не делать, ведь GC зачастую более оптимально очищает ресуры чем его ручной вызов

2024-10-02 10:06 UTC, Ropho commented on internal/agent/agent.go
> +func CollectMetrics(metrics *[]api.Metrics, counter *int64) {
для чего передавать *[]api.Metrics?
обычно достатоточно []api.Metrics

2024-10-02 10:07 UTC, Ropho commented on internal/agent/agent.go
> +	*counter += 1
интересно решение)

2024-10-02 10:08 UTC, Ropho commented on internal/agent/agent.go
> +func CollectMetrics(metrics *[]api.Metrics, counter *int64) {
Чтобы менять размер слайса?
Проще тогда его просто возвращать в return параметрах, а не передавать во входных

2024-10-02 10:10 UTC, Ropho commented on internal/agent/agent.go
> +	*counter += 1
loger все-таки пишется с двумя g
logger

2024-10-02 10:14 UTC, Ropho commented
loger пишется с двумя g - logger

2024-10-02 10:14 UTC, Ropho commented
В целом подправь агент и можно приступать к монстру - серверу)

2024-10-02 15:24 UTC, netzen86 commented on cmd/agent/main.go
> +	// устанвливаем для отображения даты и времени в логах
Исправил

2024-10-02 15:24 UTC, netzen86 commented on config/agentcfg.go
> +	"github.com/spf13/pflag"
Исправил

2024-10-02 15:52 UTC, netzen86 commented on internal/agent/agent.go
> +)
addressServer pollInterval reportInterval переместил в конфиг, имена метрик сделал анонимными они больше корме как локально в этом пакете не используются.

2024-10-02 15:54 UTC, netzen86 commented on internal/agent/agent.go
> +	runtime.GC()
Я подумал что без вызова этой функции счетчики GC не будут изменяться. Попробую убрать.

2024-10-02 16:08 UTC, netzen86 commented on internal/agent/agent.go
> +func CollectMetrics(metrics *[]api.Metrics, counter *int64) {
Исправил

2024-10-03 18:40 UTC, Ropho commented on cmd/server/main.go
> +	// saveMetricsDefaultPath = fmt.Sprintf("%s/%s", workDir, saveMetricsDefaultPath)
убрать комментарии из кода, это зачастую лежит в коде годами)))

2024-10-05 14:38 UTC, Ropho commented on cmd/server/main.go
> +	log.Println("!!! SERVER START !!!")
не использовать стандартный логгер
использовать описанный zap logger

2024-10-13 23:08 UTC, Ropho commented on cmd/agent/agent_test.go
какой-то пустой файл)
Такого не надо. Если он не используется, то лучше удалять сразу и не засорять репу

2024-10-13 23:10 UTC, Ropho commented on cmd/agent/main.go
> +	}
я бы конечно такую бизнес логику в main функции не держал а вынес в internal
Main это точка входа и выхода, логики в ней нет, он лишь вызывает эту логику в виде других функций

2024-10-13 23:12 UTC, Ropho commented on cmd/server/main.go
> +	errs := http.ListenAndServe(cfg.Endpoint, gw)
почему errs а не err

2024-10-13 23:14 UTC, Ropho commented on config/agentcfg.go
> +		agentCfg.Endpoint = os.Getenv("ADDRESS")
несколько раз повторяется "магическое" слово в коде
такое лучше выносить в переменную, чтобы не запутаться и чтобы по код стайлу было лучше

2024-10-13 23:15 UTC, Ropho commented on config/servercfg.go
> +		err = utils.RetrayFunc(retrybuilder)
retray наверное имеется в виду retry?

2024-10-13 23:15 UTC, Ropho commented on config/servercfg.go
> +					log.Println(err)
почему только здесь используется логгирование
это как-то определено или просто случайный принт?

2024-10-13 23:16 UTC, Ropho commented on config/servercfg.go
> +	ctx := context.Background()
любые инициализации, которые прокидываются в нижние слои лучше делать в мейне

2024-10-13 23:16 UTC, Ropho commented on config/servercfg.go
> +		retrybuilder := func() func() error {
почему такой сложный механизм вызова?)
зачем такие сложности?

2024-10-13 23:17 UTC, Ropho commented on config/servercfg.go
> +			log.Fatal("tables not created ", err)
не надо падать с фаталом не в main

2024-10-13 23:17 UTC, Ropho commented on config/servercfg.go
> +	// созданиe файлсторэжа
инициализации частей системы лучше выносить все же в main

2024-10-13 23:18 UTC, Ropho commented on config/servercfg.go
> +	}
эта логика не должна быть в пакете config

2024-10-13 23:20 UTC, Ropho commented on internal/agent/agent.go
очень много принтов, лучше их заменить на определенный уровень логгирования, например debug
тогда при установке логгера более высокого уровня этих записей не будет

2024-10-13 23:23 UTC, Ropho commented on internal/logger/logger.go
> +func Loger() zap.SugaredLogger {
logger с двумя g

2024-10-13 23:23 UTC, Ropho commented on internal/logger/logger.go
> +		panic(err)
не паникуем, Дима!
все хорошо!!

2024-10-13 23:24 UTC, Ropho commented on internal/repositories/db/db.go
> +	DataBaseConString string = "postgres://postgres:collectmetrics@localhost/collectmetrics?sslmode=disable"
можно тоже получать из конфига

2024-10-13 23:24 UTC, Ropho commented on internal/repositories/db/db.go
> +func NewDBStorage(ctx context.Context, param string) (*DBStorage, error) {
отлично!

2024-10-13 23:25 UTC, Ropho commented on internal/repositories/db/db.go
> +	dbstorage.DB, err = sql.Open("pgx", param)
разве не рекомендуют вызвать функцию ping чтобы проверить, что соединение действительно установилось?

2024-10-13 23:25 UTC, Ropho commented on internal/repositories/db/db.go
> +		return &DBStorage{}, fmt.Errorf("cannot connect fo data base %w", err)
лучше возвращать nil первым параметром

2024-10-13 23:28 UTC, Ropho commented on internal/handlers/handlers_test.go
пустой файл без тестов (
если нет тестов, то лучше это скрыть,  удалив файл)

2024-10-13 23:29 UTC, Ropho commented on internal/router/router.go
> +	// gw.Use(handlers.WithLogging)
почему не получилось через use?

2024-10-13 23:31 UTC, Ropho requested changes
Основная просьба это вынести всю логику по инициализации в main, а логику бизнеса из мейна убрать

Я очень хочу видеть, как слой репозитория иниализируется в мейне

2024-10-14 16:40 UTC, netzen86 commented on cmd/agent/agent_test.go
Оставил, так как хочу дописать тесты. Да и тесты без него не проходят. Постараюсь как можно быстрее дописать тесты.

2024-10-14 16:42 UTC, netzen86 commented on cmd/agent/main.go
> +	}
Исправил.

2024-10-14 16:44 UTC, netzen86 commented on cmd/server/main.go
> +	errs := http.ListenAndServe(cfg.Endpoint, gw)
В первых итерациях я в этом месте пытался обработать две ошибке по этому использовал разные переменные для ошибок, в последствии этот кусок переписался. 
Исправил на err.

2024-10-14 16:57 UTC, netzen86 commented on config/agentcfg.go
> +		agentCfg.Endpoint = os.Getenv("ADDRESS")
Исправил

2024-10-14 17:56 UTC, netzen86 commented on config/servercfg.go
> +		err = utils.RetrayFunc(retrybuilder)
Да имелось ввиду retry. Исправил.

2024-10-14 18:01 UTC, netzen86 commented on config/servercfg.go
> +					log.Println(err)
Это анонимная фикция которая используется как аргумент для функции повторения запросов.
Переделаю на кастомный логгер как только с ним разберусь.

2024-10-14 18:09 UTC, netzen86 commented on config/servercfg.go
> +	ctx := context.Background()
Не понял замечание... Из мэйна запускается функция GetServerCfg  в которой и запускается initSrv, вроде ничего на нижние слои не прокидываются...
Или сделать initSrv публичной отдельной функцией и в мэйне запускать?

2024-10-14 18:10 UTC, netzen86 commented on config/servercfg.go
> +		retrybuilder := func() func() error {
для того что бы повторить попытку в случаи неудачи. Переписать функцию повторной отправки запросов?

2024-10-14 18:11 UTC, netzen86 commented on config/servercfg.go
> +			log.Fatal("tables not created ", err)
Исправил

2024-10-14 18:12 UTC, netzen86 commented on config/servercfg.go
> +	// созданиe файлсторэжа
Получается функцию initSrv вызываю из мэйна? или объявить ее тоже в мэйне?

2024-10-14 18:46 UTC, netzen86 commented on config/servercfg.go
> +	}
Перенес в пакет internal/server

2024-10-14 18:47 UTC, netzen86 commented on internal/agent/agent.go
Хорошо, буду исправлять

2024-10-14 19:00 UTC, netzen86 commented on internal/logger/logger.go
> +		panic(err)
Исправил

2024-10-14 19:04 UTC, netzen86 commented on internal/repositories/db/db.go
> +	DataBaseConString string = "postgres://postgres:collectmetrics@localhost/collectmetrics?sslmode=disable"
Эту константу я использовал как подсказку, сделаю из нее комментарий.

2024-10-14 19:11 UTC, netzen86 commented on internal/repositories/db/db.go
> +	dbstorage.DB, err = sql.Open("pgx", param)
Добавил вызов функции PingContext

2024-10-14 19:12 UTC, netzen86 commented on internal/repositories/db/db.go
> +		return &DBStorage{}, fmt.Errorf("cannot connect fo data base %w", err)
Исправил

2024-10-14 19:13 UTC, netzen86 commented on internal/handlers/handlers_test.go
допишу тесты. если удалю этот файл то не проходят автотерсы в репе

2024-10-14 19:18 UTC, netzen86 commented on internal/router/router.go
> +	// gw.Use(handlers.WithLogging)
use принимает http.Handler, а я все хендлеры сдела http.HandlerFunc для того что бы передавать им параметры. Буду переписывать с использованием структуры что бы при инициализации принимать параметры.

2024-10-15 16:13 UTC, netzen86 commented on internal/logger/logger.go
> +func Loger() zap.SugaredLogger {
исправил

2024-10-20 22:26 UTC, Ropho commented on config/servercfg.go
> +	// созданиe файлсторэжа
странно выглядит что инициализация сервера производится внутри файла конфига. Ведь север - это зависимость для конфига.
Работа по созданию зависимостей - это удел main

2024-10-20 22:27 UTC, Ropho commented on config/servercfg.go
> +	// созданиe файлсторэжа
Меня смущает, почему config принимает решение о создании storage внутри себя

2024-10-20 22:32 UTC, Ropho commented on internal/repositories/db/db.go
> +	defer rows.Close()
на самом деле здесь надо обрабатывать ошибку по-хорошему

2024-10-20 22:33 UTC, Ropho commented on internal/repositories/db/db.go
> +	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
в чем тут идея создания такого timeout?

2024-10-20 22:38 UTC, Ropho approved these changes

2024-10-20 22:40 UTC, Ropho commented on cmd/server/main.go
> +	}
поясни пж что это и зачем

2024-10-20 22:40 UTC, Ropho commented on internal/handlers/handlers_test.go
файл без тестов)

2024-10-20 22:41 UTC, Ropho commented on internal/repositories/memstorage/memstorage_test.go
файл без тестов)

2024-10-22 16:58 UTC, netzen86 commented on internal/repositories/db/db.go
> +	defer rows.Close()
как то дополнительно обработать? retry сделать?

2024-10-22 16:59 UTC, netzen86 commented on internal/repositories/db/db.go
> +	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
я насколько я помню в задании было условие создать контекст с таймаутом...

2024-10-22 17:02 UTC, netzen86 commented on cmd/server/main.go
> +	}
здесь создаются таблицы counter и gauge если для хранилища выбрана БД

2024-10-22 17:02 UTC, netzen86 commented on internal/handlers/handlers_test.go
обязательно допишу

2024-10-22 17:03 UTC, netzen86 commented on internal/repositories/memstorage/memstorage_test.go
обязательно допишу

2024-11-13 18:46 UTC, merged